source 'https://github.com/cocoapods/specs.git'

platform :ios, '12.0'

inhibit_all_warnings!

#install! 'cocoapods',
#  disable_input_output_paths: true

target 'AYiOSProject' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  pod 'AFNetworking', '~> 4.0.1'                            # 网络请求
#  pod 'BabyBluetooth', '~> 0.7.0'                           # 蓝牙
  pod 'BRPickerView', '~> 2.8.1'                            # 选择器
  pod 'CHTCollectionViewWaterfallLayout/ObjC', '~> 0.9.10'  # 瀑布流
  pod 'CRBoxInputView', '~> 1.2.2'                          # 短信验证码输入框
#  pod 'DGCharts', '~> 5.0.0'                                # 图表
  pod 'FDFullscreenPopGesture', '~> 1.1'                    # 全屏手势返回
#  pod 'FSCalendar', '~> 2.8.4'                              # 日历
#  pod 'HDRatingStarView', '~> 1.2.0'                        # 评分星级
  pod 'IQKeyboardManager', '~> 6.5.16'                      # 键盘管理
  pod 'JKCategories', '~> 1.9.3'                            # 扩展类
  pod 'JXCategoryView', '~> 1.6.1'                          # 分类切换
#  pod 'JXPagingView/Pager', '~> 2.1.2'                      # 分类子项
  pod 'LEEAlert', '~> 1.6.4'                                # Alert弹窗
  pod 'Masonry', '~> 1.1.0'                                 # 自动布局
  pod 'MBProgressHUD', '~> 1.2.0'                           # 提示框
  pod 'MJRefresh', '~> 3.7.6'                               # 下拉刷新
  pod 'MMKV', '~> 1.3.2'                                    # MMKV存储
  pod 'ReactiveObjC', '~> 3.1.1'                            # RAC
  pod 'SDWebImage', '~> 5.18.10'                            # 网络图片
#  pod 'SGQRCode', '~> 4.1.0'                                # 二维码扫描
  pod 'SocketRocket', '~> 0.7.0'                            # 通讯套接字
  pod 'TYAttributedLabel', '~> 2.6.9'                       # 富文本
  pod 'TZImagePickerController', '~> 3.8.4'                 # 图片选择器
  pod 'YTKNetwork', '~> 3.0.6'                              # 网络请求
  pod 'YYCategories', '~> 1.0.4'
#  pod 'YYText', '~> 1.0.7'
  pod 'YYModel', '~> 1.0.4'

end

post_install do |installer|
  # 消除警告
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
      target.build_configurations.each do |config|
        config.build_settings["ENABLE_BITCODE"] = "NO"
      end
    end
  end
  # M芯片报错修复
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
